# Employee Management System

## Developed By
Eric Rathod

## Technologies Used
- Python
- SQLite
- Pandas
- Google Colab

## Features
- Add Employee
- View Employees
- Search Employee
- Update Employee
- Delete Employee

Creating Database

In [1]:
import sqlite3

conn = sqlite3.connect("employee_management.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS employees(
    employee_id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT,
    department TEXT,
    job_title TEXT,
    email TEXT,
    phone TEXT,
    salary REAL,
    joining_date TEXT
)
""")

conn.commit()
conn.close()

print("Database Created Successfully")

Database Created Successfully

Adding Employee

In [2]:
import sqlite3

conn = sqlite3.connect("employee_management.db")
cursor = conn.cursor()

cursor.execute("""
INSERT INTO employees
(full_name, department, job_title, email, phone, salary, joining_date)
VALUES
(
'Eric Rathod',
'IT',
'Developer',
'eric@test.com',
'6479619811',
65000,
'2026-01-01'
)
""")

conn.commit()
conn.close()

print("Employee Added Successfully")

Employee Added Successfully

View Employees

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee_management.db")

df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

conn.close()

df

,employee_id,full_name,department,job_title,email,phone,salary,joining_date
0,1,Eric Rathod,IT,Developer,eric@test.com,6479619811,65000.0,2026-01-01

Adding More Employees

In [4]:
import sqlite3

conn = sqlite3.connect("employee_management.db")
cursor = conn.cursor()

employees = [
    ("Amit Patel", "HR", "HR Assistant", "amit@test.com", "6471112222", 52000, "2026-02-10"),
    ("Sara Khan", "Finance", "Accountant", "sara@test.com", "6472223333", 58000, "2026-03-15"),
    ("John Smith", "IT", "System Analyst", "john@test.com", "6473334444", 70000, "2026-04-01"),
    ("Priya Sharma", "Operations", "Operations Coordinator", "priya@test.com", "6474445555", 56000, "2026-05-20")
]

cursor.executemany("""
INSERT INTO employees
(full_name, department, job_title, email, phone, salary, joining_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", employees)

conn.commit()
conn.close()

print("Multiple employees added successfully")

Multiple employees added successfully

Viewing Updated Table

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee_management.db")

df = pd.read_sql_query("SELECT * FROM employees", conn)

conn.close()

df

,employee_id,full_name,department,job_title,email,phone,salary,joining_date
0,1,Eric Rathod,IT,Developer,eric@test.com,6479619811,65000.0,2026-01-01
1,2,Amit Patel,HR,HR Assistant,amit@test.com,6471112222,52000.0,2026-02-10
2,3,Sara Khan,Finance,Accountant,sara@test.com,6472223333,58000.0,2026-03-15
3,4,John Smith,IT,System Analyst,john@test.com,6473334444,70000.0,2026-04-01
4,5,Priya Sharma,Operations,Operations Coordinator,priya@test.com,6474445555,56000.0,2026-05-20

Search Employee

In [6]:
import sqlite3
import pandas as pd

search_name = input("Enter employee name to search: ")

conn = sqlite3.connect("employee_management.db")

query = """
SELECT * FROM employees
WHERE full_name LIKE ?
"""

df = pd.read_sql_query(query, conn, params=('%' + search_name + '%',))

conn.close()

df

Enter employee name to search: Eric

,employee_id,full_name,department,job_title,email,phone,salary,joining_date
0,1,Eric Rathod,IT,Developer,eric@test.com,6479619811,65000.0,2026-01-01

Update Employee

In [7]:
import sqlite3

employee_id = int(input("Enter Employee ID to update: "))
new_department = input("Enter new department: ")
new_job_title = input("Enter new job title: ")
new_salary = float(input("Enter new salary: "))

conn = sqlite3.connect("employee_management.db")
cursor = conn.cursor()

cursor.execute("""
UPDATE employees
SET department = ?, job_title = ?, salary = ?
WHERE employee_id = ?
""", (new_department, new_job_title, new_salary, employee_id))

conn.commit()
conn.close()

print("Employee Updated Successfully")

Enter Employee ID to update: 1
Enter new department: IT
Enter new job title: Junior Developer
Enter new salary: 68000
Employee Updated Successfully

Delete Employee

In [8]:
import sqlite3

employee_id = int(input("Enter Employee ID to delete: "))

conn = sqlite3.connect("employee_management.db")
cursor = conn.cursor()

cursor.execute("""
DELETE FROM employees
WHERE employee_id = ?
""", (employee_id,))

conn.commit()
conn.close()

print("Employee Deleted Successfully")

Enter Employee ID to delete: 5
Employee Deleted Successfully

Verify Deletion

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee_management.db")

df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

conn.close()

df

,employee_id,full_name,department,job_title,email,phone,salary,joining_date
0,1,Eric Rathod,IT,Junior Developer,eric@test.com,6479619811,68000.0,2026-01-01
1,2,Amit Patel,HR,HR Assistant,amit@test.com,6471112222,52000.0,2026-02-10
2,3,Sara Khan,Finance,Accountant,sara@test.com,6472223333,58000.0,2026-03-15
3,4,John Smith,IT,System Analyst,john@test.com,6473334444,70000.0,2026-04-01

Department Report

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee_management.db")

query = """
SELECT
department,
COUNT(*) AS Total_Employees,
ROUND(AVG(salary),2) AS Average_Salary
FROM employees
GROUP BY department
"""

report = pd.read_sql_query(query, conn)

conn.close()

report

  department  Total_Employees  Average_Salary
0    Finance                1         58000.0
1         HR                1         52000.0
2         IT                2         69000.0